# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2fe2fc5c2265af157bf18f2ec234d53aacbd8a817027e4ac12dfe4ac67216aaf58cf5b6d0c201e271d2e2344454efa56f3a2e492e267eba5a26e8639c664160

test:
  secret_key_base: d138410a2d66c1577829e2963abe2f56f89f5460568a680af15d86f440af9451f49d4045752db3fd769a00973ffa5516fe081879682ce51c3625d0971850b33e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
